chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.MessageListView.as_view(), name='list'),
    url(r'^testmessage/$', views.MessageListTestView.as_view(), name='test-list'),
    url(r'^error/$', views.MessageErrorView.as_view(), name='error'),
    url(r'^consultant-room/(?P<pk>[0-9]+)$', views.MessageRoomView.as_view(), name='consultant-room'),
    url(r'^tbase-room/(?P<pk>[0-9]+)$', views.TBaseMessageRoomView.as_view(), name='tbase-room'),
    url(r'^search/$', views.UserSearchView.as_view(), name='search'),
]

school/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from payment import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  # url(r'^registration/$', TemplateView.as_view(template_name="registration/reg.html")),
                  url(r'^registration/$', views.TestView.as_view()),
                  url(r'^about/$', TemplateView.as_view(template_name="registration/about.html")),
                  url(r'^faq/$', TemplateView.as_view(template_name="faq.html")),
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'password_change/$', auth_views.password_change,
                      {'template_name': 'registration/change_password.html'},
                      name='password-change'),
                  url(r'password_reset/$', auth_views.password_reset,
                      {'template_name': 'registration/password_reset.html'},
                      name='password-reset'),
                  url(r'^password_reset_done/$', auth_views.password_reset_done,
                      {'template_name': 'registration/password_reset_done.html'},
                      name='password_reset_done'),

                  url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                      auth_views.password_reset_confirm,
                      {'post_reset_redirect': '/password_done/'}, name='password_reset_confirm'),

                  url(r'^password_done/$', auth_views.password_reset_complete),

                  url(r'^password-change-done/$', auth_views.password_change_done,
                      {'template_name': 'registration/password_change_done.html'},
                      name='password_change_done'),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'', include('news.urls')),
                  url(r'^articles/', include('articles.urls')),
                  url(r'^chat/', include('chat.urls')),
                  url(r'^training/', include('training.urls')),
                  url(r'^photorepost/', include('photorepost.urls')),
                  url(r'^food/', include('food.urls')),
                  url(r'^quiz/', include('quiz.urls')),
                  url(r'^users/', include('users.urls')),
                  url(r'^payment/', include('payment.urls')),
                  url(r'^support/', include('supportapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^profile/edit/$', views.UserProfileEditView.as_view(), name='profile-edit'),
    url(r'^profile/add_in_group/$', views.UserAddToInGroupView.as_view(), name='add-in-group'),
    url(r'^profile/family/edit/(?P<pk>[0-9]+)/$', views.UserProfileFamilyEditView.as_view(), name='profile-family-edit'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/password-edit/$', views.UserPasswordEditView.as_view(), name='password-edit'),
    url(r'^all/$', views.users_list, name='users-list'),
]

chat/models.py
from django.db import models
from django.utils import timezone

from users.models import User


class Message(models.Model):
    text = models.TextField()
    img = models.ImageField(upload_to='message', null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    sender = models.ForeignKey(User, related_name='sender_messages')
    recipent = models.ForeignKey(User, related_name='recipent_messages')
    private_type = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    is_new = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class NewMessage(models.Model):
    user = models.ForeignKey(User, related_name='new_messages')
    sender = models.ForeignKey(User,related_name='new_sender_messages')
    message = models.ForeignKey(Message, related_name='new_messages')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Новые сообщения'
        verbose_name_plural = 'Новые сообщения'

chat/forms.py
from django import forms

from chat.models import Message


class MessageCreateForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('sender', 'recipent', 'text', 'img')

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, TemplateView
from django.core.urlresolvers import reverse_lazy
from common.mixins import PayCheck
from django.db.models import Q
import datetime
from itertools import chain
from datetime import date, timedelta
from django.core.paginator import (Paginator, EmptyPage,
                                   PageNotAnInteger, InvalidPage,
                                   )

from chat.forms import MessageCreateForm
from chat.models import Message, NewMessage
from users.models import User


class MessageListView(LoginRequiredMixin, PayCheck,View):

    def get_message_user_ids(self,user):
        ids = Message.objects.values_list('sender_id', 'recipent_id'). \
            filter(Q(recipent_id=user.pk) | Q(sender_id=user.pk))
        users_ids = []
        for msg in ids:
            a, b = msg
            if a != user.pk:
                users_ids.append(a)
            if b != user.pk:
                users_ids.append(b)
        return users_ids

    def get(self, request, *args, **kwargs):
        template_name = 'chat/message_list.html'
        if request.user.is_consultant_manager():
            users_ids = self.get_message_user_ids(request.user)
            users = User.objects.filter(id__in=users_ids)
        elif request.user.is_base_user():
            users = User.objects.filter(type=User.ASSISTENT)
        elif request.user.is_food_user():
            users = User.objects.filter(type=User.ASSISTENT)
        elif request.user.is_children_user():
            users = User.objects.filter(type__in=[User.ZUBAREVA, User.PEDIATRICIAN, User.GV])
        elif request.user.is_food_plus_sport_user():
            users = User.objects.filter(type__in=[User.ASSISTENT, User.COACH, User.NEUROLOGIST])
        elif request.user.is_food_plus_specialist_user():
            users = User.consultants_objects.filter(~Q(type__in=[User.ASSISTENT, User.GV, User.COACH, User.PEDIATRICIAN, User.ZUBAREVA, User.GASTRO]))
        elif request.user.is_family_user():
            users = User.consultants_objects.filter(~Q(type__in=[User.ASSISTENT, User.GV, User.DIETOLOG, User.GASTROTWO]))
        else:
            users = User.consultants_objects.filter(~Q(type__in=[User.ASSISTENT, User.GV, User.PEDIATRICIAN, User.DIETOLOG, User.GASTROTWO]))
        message_counts = NewMessage.objects.filter(user=request.user).count()
        ctx = dict()
        ctx['message_counts'] = message_counts
        ctx['consultants'] = users
        return render(request, template_name, ctx)


class MessageListTestView(LoginRequiredMixin,View):

    def get_message_user_ids(self,user):
        ids = set(list(Message.objects.values_list('sender_id','recipent_id'). \
            filter(Q(recipent_id=user.pk) | Q(sender_id=user.pk))))
        users_ids = []
        for msg in ids:
            a,b = msg
            if a != user.pk:
                users_ids.append(a)
            if b != user.pk:
                users_ids.append(b)
        return users_ids

    # def get_message_consultant_ids(self,):

    def get(self, request, *args, **kwargs):
        page = self.request.GET.get('page', None)
        template_name = 'chat/message_test_list.html'
        if request.user.is_consultant_manager():
            users_ids = self.get_message_user_ids(request.user)
            users = User.objects.filter(id__in=users_ids)
        elif request.user.is_food_user():
            users = User.objects.filter(type=User.ASSISTENT)
        elif request.user.is_children_user():
            users = User.objects.filter(type__in=[User.ZUBAREVA, User.PEDIATRICIAN, User.GV])
        elif request.user.is_food_plus_sport_user():
            users = User.objects.filter(type__in=[User.ASSISTENT, User.COACH, User.NEUROLOGIST])
        elif request.user.is_family_user():
            users = User.consultants_objects.filter(~Q(type__in=[User.ASSISTENT, User.GV]))
        else:
            users = User.consultants_objects.filter(~Q(type__in=[User.ASSISTENT, User.GV, User.PEDIATRICIAN]))
        message_counts = NewMessage.objects.filter(user=request.user).count()
        new_consultants = User.objects.filter(id__in=list(request.user.new_messages.values_list('sender_id', flat=True)))
        consultants = users.exclude(id__in=new_consultants)

        # new_consultants = new_consultants.order_by('sender_messages__created')
        all_users = list(chain(new_consultants, consultants))

        paginator = Paginator(all_users, 50)
        try:
            consultants = paginator.page(page)
        except PageNotAnInteger:
            consultants = paginator.page(1)
        except EmptyPage:
            consultants = paginator.page(paginator.num_pages)
        ctx = dict()
        ctx['message_counts'] = message_counts
        ctx['consultants'] = consultants
        # ctx['new_consultants'] = new_consultants
        return render(request, template_name, ctx)


class MessageRoomView(LoginRequiredMixin,View):
    template_name = 'chat/message_open.html'

    def get(self, request, *args, **kwargs):
        consultant = User.objects.get(pk=kwargs.get('pk'))
        messages = Message.objects.filter(sender__in=[request.user, consultant],
                                          recipent__in=[request.user, consultant]).\
            order_by('created')

        NewMessage.objects.filter(message__in=messages, user=request.user).delete()
        message_form = MessageCreateForm()
        ctx = {}
        ctx['consultant'] = consultant
        ctx['messages'] = messages
        ctx['message_form'] = message_form
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        today = date.today()
        print("today", today)
        count_messages = Message.objects.filter(sender=request.user, recipent_id=request.POST.get('recipent'), created__date=today).count()
        print(count_messages)
        if count_messages < 3:
            message_form = MessageCreateForm(request.POST, request.FILES)
            if message_form.is_valid():
                message = message_form.save()
                new_message = NewMessage()
                new_message.message = message
                new_message.user = message.recipent
                new_message.sender = message.sender
                new_message.save()
                pk = kwargs.get('pk')
                to_redirect = reverse_lazy('chat:consultant-room', kwargs={'pk': pk})
                return redirect(to_redirect)
        else:
            return render(request, 'chat/message_error.html')



class TBaseMessageRoomView(LoginRequiredMixin,View):
    template_name = 'chat/message_open.html'

    def get(self, request, *args, **kwargs):
        consultant = User.objects.get(pk=kwargs.get('pk'))
        messages = Message.objects.filter(sender__in=[request.user, consultant],
                                          recipent__in=[request.user, consultant]).\
            order_by('created')

        NewMessage.objects.filter(message__in=messages, user=request.user).delete()
        message_form = MessageCreateForm()
        ctx = {}
        ctx['consultant'] = consultant
        ctx['messages'] = messages
        ctx['message_form'] = message_form
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        today = date.today()
        print("today", today)
        count_messages = Message.objects.filter(sender=request.user, recipent_id=request.POST.get('recipent'), created__date=today).count()
        print(count_messages)
        if count_messages < 1:
            message_form = MessageCreateForm(request.POST, request.FILES)
            if message_form.is_valid():
                message = message_form.save()
                new_message = NewMessage()
                new_message.message = message
                new_message.user = message.recipent
                new_message.sender = message.sender
                new_message.save()
                pk = kwargs.get('pk')
                to_redirect = reverse_lazy('chat:tbase-room', kwargs={'pk': pk})
                return redirect(to_redirect)
        else:
            return render(request, 'chat/message_error.html')




class MessageErrorView(LoginRequiredMixin,TemplateView):
    template_name = 'chat/message_error.html'



class UserSearchView(ListView):
    model = Message
    template_name = "users_search.html"



    def get(self, request, *args, **kwargs):
        ctx = dict()
        question = request.GET.get('q')
        if question is not None:
            users = User.objects.filter(Q(first_name__icontains=question) | Q(last_name__icontains=question))

        ctx['users'] = users
        return render(request, self.template_name, ctx)

chat/templates/chat/message_error.html
{% extends "base.html" %}
{% load staticfiles %}
{% load message_tags %}
{% load common_tags %}
{% load thumbnail %}
{% block content %}

<div class="panel panel-plain panel-rounded">

    <div class="panel-body">
        <div class="row">

            <div class="col-md-9">
                <div class="alert alert-danger" role="alert" style="padding: 5px;">
                    Лимит сообщений к специалисту за сегодня превышен. Через 24 часа вы сможете возобновить свой сеанс.
                </div>
            </div>


        </div><!-- /.row -->

    </div><!-- .panel-body -->
</div>

{% endblock %}

chat/templates/chat/message_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load message_tags %}
{% load common_tags %}
{% load thumbnail %}
{% block content %}

<div class="alert alert-success alert-simple alert-dismissible fade in iconic-alert m-b-lg" role="alert">

							<div class="alert-icon">
								<span class="gcon gcon-emoji-happy centered-xy"></span>
							</div>
							<p style="font-size: 12px!important;"> {% if request.user.get_tariff_code != 'base' %}  В течение суток Вы можете задать максимум 3 самые важных вопроса, остальные вопросы пишите в комментариях в разделе "Новости".{% else %}  Вы cможете написать 1 технический вопрос в сутки, ассистенту {% endif %}</p>
						</div>


<div class="panel panel-plain panel-rounded">

    <div class="panel-body">
        <div class="row">


            <div class="col-md-12">
                <ul class="dropdown-menu xl-dropdown p-b-0 p-t-0 dropdown-demo m-t m-b-lg">
                    <li class="dropdown-header text-uppercase has-divider hidden-xs">
                        Уведомления
                        <span class="label label-success m-l">{{ message_counts }} новых</span>
                    </li>
                    <li>
                        <ul class="rs-inner-dropdown has-divider media-menu rs-scroll-custom" tabindex="3">
                            {% for c in consultants %}
                                <!-- Для новых сообщений добавляем класс"new" <li class="new"></li>-->
                                {% if request.user|is_new_messages_for_user:c.pk %}
                                    <li class="new">

                                        {% if request.user.get_tariff_code == 'base' %}
                                        <a style="padding-top: 20px;padding-bottom: 20px;"
                                           href="{% url 'chat:tbase-room' c.pk %}">
                                         {% else %}
                                            <a style="padding-top: 20px;padding-bottom: 20px;"
                                           href="{% url 'chat:consultant-room' c.pk %}">
                                        {% endif %}

                                            {% thumbnail c.get_avatar "60x60" as im %}
                                                <img style="object-fit: none;" src="{{ im.url }}" alt="Avatar" class="media img-circle">
                                            {% endthumbnail %}
                                            <span class="id">{{ c.get_full_name }}</span>
                                             <span style="margin: 0; color: #2e7401;" class="time small"> Тариф: {{ c.get_tariff_name }}</span>
                                            <span style="margin: 0;" class="time small">{{ request.user|last_message_time:c.pk }}</span>
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% for c in consultants %}

                                {% if not request.user|is_new_messages_for_user:c.pk %}
                                <li>

                                    {% if request.user.get_tariff_code == 'base' %}
                                        <a style="padding-top: 20px;padding-bottom: 20px;"
                                           href="{% url 'chat:tbase-room' c.pk %}">
                                     {% else %}
                                            <a style="padding-top: 20px;padding-bottom: 20px;"
                                           href="{% url 'chat:consultant-room' c.pk %}">
                                     {% endif %}

                                        {% thumbnail c.get_avatar "60x60" as im %}
                                            <img style="object-fit: none;" src="{{ im.url }}" alt="Avatar" class="media img-circle">
                                        {% endthumbnail %}
                                        <span class="id">{{ c.get_full_name }}</span>
                                        <span class="time small">{{ request.user|last_message_time:c.pk }}</span>
                                    </a>
                                </li>

                            {% endif %}
                            {% endfor %}

                        </ul>
                    </li>


                </ul>
            </div><!-- /.col-md-4 -->


        </div><!-- /.row -->

    </div><!-- .panel-body -->
</div>

{% endblock %}

{% block h1_title %}
    Специалисты
{% endblock %}

{% block breadcrumbs %}
    <li class="active">Специалисты</li>
{% endblock %}

chat/templates/chat/message_open.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}

    <div class="col-md-11 col-lg-11">
    <!-- Комментарии -->
    <div class="panel panel-plain panel-rounded">
        <div class="panel-heading borderless">
            <h3 class="panel-title">{{ c }}</h3>
            <p style="margin: 0;" class="media-subheading text-muted small">{{ consultant.get_full_name }}</p>
            <p style="margin: 0;padding: 0;line-height: 105%;" class="media-subheading text-muted small"> Тариф: {{ consultant.get_tariff_name }}</p>
        </div><!-- /.panel-heading -->
        <div class="panel-body">
            <ul style="height: 400px; overflow-y: scroll; padding-right: 5%;" class="media-list" id="media-messages">
                {% for msg in messages %}

                <li class="media">
                    <div class="media-left media-object-sm">
                        <a href="{% url 'users:profile' %}">
                            {% thumbnail msg.sender.get_avatar "50x50" as im %}
                                <img  src="{{ im.url }}" alt="Avatar" class="media-object img-circle">
                            {% endthumbnail %}
                        </a>
                    </div><!-- /.media-left -->
                    <div class="media-body">
                        <h4 class="media-heading bg-d">{{ msg.sender.get_full_name }}</h4>
                        <p class="media-subheading text-muted small">{{ msg.created }}</p>
                        <p>{{ msg.text|safe }}</p>
                        {% thumbnail msg.img "1200" as big %}
                            {% thumbnail msg.img "55x55" as im %}
                                <a style="width: auto;display: block;" href="{{ big.url}}"  target="_blank">
                                    <img style="display: block;"  src="{{ im.url }}" alt="Avatar" class="media-object">
                                </a>
                            {% endthumbnail %}
                        {% endthumbnail %}
                    </div><!-- /.media-body -->
                </li>
                <hr>
                {% endfor %}

            </ul><!-- /.media-list -->
             <br>
            <form method="post"  enctype="multipart/form-data">
                {% csrf_token %}
                <div style="" class="form-group">
                    <label>Сообщение <b style="color: #902b2b;">*</b></label>
                    <input type="hidden" name="{{ message_form.sender.html_name }}" value="{{ request.user.pk }}">
                    <input type="hidden" name="{{ message_form.recipent.html_name }}" value="{{ consultant.pk }}">
                    <textarea id="message-text" name="{{ message_form.text.html_name }}"class="form-control" placeholder="Здравствуйте, ...."
                              style="height: 100px;" required></textarea>
                    <div style="display: none;">
                        <br>
                        <label>Прикрепить фото (макс 4 Мб):</label>
                        <input type="file" class="form-control" name="{{ message_form.img.html_name }}">
                        <br>
                    </div>
                    <button class="btn btn-success btn-block rs-btn-icon icon-block m-b"><span
                            class="fa fa-comment-o icon-btn m-r"></span>Отправить
                    </button>
                </div>
            </form>



        </div><!-- .panel-body -->
    </div>
    <!-- End Комментарии -->
    </div>

{% endblock %}

{% block h1_title %}
    Сообщения

{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'chat:list' %}">Сообщения</a></li>
    <li class="active">{{ consultant.get_full_name }}</li>
{% endblock %}


{% block js_block %}
    <script type="text/javascript">
        $(function(){
            var div = $("#media-messages");
            div.scrollTop(div.prop('scrollHeight'));
            $('html,body').stop().animate({ scrollTop: $('#message-text').offset().top }, 1000);

        });
    </script>
{% endblock %}

chat/templates/chat/message_test_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load message_tags %}
{% load common_tags %}
{% load thumbnail %}
{% block content %}

<div class="panel panel-plain panel-rounded">
 <div class="panel-body">
    <div class="row">
        {% if request.user.get_tariff_name == None %}


                        <form action="{% url 'chat:search' %}"  method="get">
                    <div class="col-md-4">
                        <div class="form-group">
                            <input id="search" name="q" type="text" class="form-control" placeholder="Поиск">
                        </div>
                    </div>
                            <div style="display: none;" class="col-md-4">
                        <div class="form-group">
                            <input id="date_created" name="date_created" type="text" class="form-control" placeholder="Дата">
                        </div>
                    </div>
                        <div class="col-md-2">
                            <div class="form-group">
                            <button class="btn btn-primary btn-block">Поиск</button>
                            </div>
                        </div>
                              <div class="col-md-4">
                                <p style="color: #4a89dc; line-height: 1; border: 1px solid#4a89dc; padding: 1.5% 1%; border-radius: 3px;">Поиск по фамилии <b>ИЛИ</b> по имени <br><span style="font-size: 11px;">(Желательно по фамилии, быстрее найдете).</span></p>
                            </div>
            </form>
    {% else %}


            {% endif %}
    </div>



        <div class="row">
            <div class="col-md-10">
                <ul class="dropdown-menu xl-dropdown p-b-0 p-t-0 dropdown-demo m-t m-b-lg">
                    <li class="dropdown-header text-uppercase has-divider hidden-xs">
                        Уведомления
                        <span class="label label-success m-l">{{ message_counts }} новых</span>
                    </li>
                    <li>
                        <ul class="rs-inner-dropdown has-divider media-menu rs-scroll-custom" tabindex="3">
                            {% for c in consultants %}
                                <!-- Для новых сообщений добавляем класс"new" <li class="new"></li>-->
                                {% if request.user|is_new_messages_for_user:c.pk %}
                                    <li class="new">
                                        <a style="padding-top: 20px;padding-bottom: 20px;"
                                           href="{% url 'chat:consultant-room' c.pk %}">
                                            {% thumbnail c.get_avatar "60x60" as im %}
                                                <img style="object-fit: none;" src="{{ im.url }}" alt="Avatar" class="media img-circle">
                                            {% endthumbnail %}
                                            <span class="id">{{ c.get_full_name }}</span>
                                             <span style="margin: 0; color: #2e7401;" class="time small"> Тариф: {{ c.get_tariff_name }}</span>
                                            <span style="margin: 0;" class="time small">{{ request.user|last_message_time:c.pk }}</span>
                                        </a>
                                    </li>
                                {% else %}
                                <li>
                                    <a style="padding-top: 20px;padding-bottom: 20px;"
                                       href="{% url 'chat:consultant-room' c.pk %}">
                                        {% thumbnail c.get_avatar "60x60" as im %}
                                            <img style="object-fit: none;" src="{{ im.url }}" alt="Avatar" class="media img-circle">
                                        {% endthumbnail %}
                                        <span class="id">{{ c.get_full_name }}</span>
                                        <span style="margin: 0; color: #2e7401;" class="time small"> Тариф: {{ c.get_tariff_name }}</span>
                                        <span class="time small">{{ request.user|last_message_time:c.pk }}</span>
                                    </a>
                                </li>

                            {% endif %}
                            {% endfor %}

                        </ul>

                    </li>
                    <li>

        <ul class="pagination pagination-centered">
            {% if consultants.has_previous %}
                <li><a href="?page=1"><<</a></li>
                <li><a href="?page={{ consultants.previous_page_number }}"><</a></li>
            {% endif %}

            {% for i in consultants.paginator.page_range %}
                <li {% if consultants.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}

            {% if consultants.has_next %}
                <li><a href="?page={{ consultants.next_page_number }}">></a></li>
                <li><a href="?page={{ consultants.paginator.num_pages }}">>></a></li>
            {% endif %}
        </ul>

                    </li>


                </ul>
            </div><!-- /.col-md-4 -->


        </div><!-- /.row -->

    </div><!-- .panel-body -->
</div>

{% endblock %}

{% block h1_title %}
    Специалисты
{% endblock %}

{% block breadcrumbs %}
    <li class="active">Специалисты</li>
{% endblock %}

{% block js_block %}
  $(function(){
     console.log("It's working");
  });
{% endblock %}