chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.MessageListView.as_view(), name='list'),
    url(r'^testmessage/$', views.MessageListTestView.as_view(), name='test-list'),
    url(r'^error/$', views.MessageErrorView.as_view(), name='error'),
    url(r'^consultant-room/(?P<pk>[0-9]+)$', views.MessageRoomView.as_view(), name='consultant-room'),
    url(r'^tbase-room/(?P<pk>[0-9]+)$', views.TBaseMessageRoomView.as_view(), name='tbase-room'),
    url(r'^search/$', views.UserSearchView.as_view(), name='search'),
]

news/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'news'
urlpatterns = [
    # url(r'^$', views.news_list, name='list'),
    url(r'^$', views.NewsListView.as_view(), name='list'),
    #url(r'^news/(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsDetailView.as_view(), name='detail'),
    url(r'^not/$', views.NotcommentListView.as_view(), name='not-list'),
    #url(r'^news/(?P<pk>\d+)/comment/$', views.add_comment_to_news, name='add_comment_to_news'),
    url(r'^add_comment/$', views.add_comment, name='add-comment'),
    url(r'^news/comments/$', views.CommentListView.as_view(), name='list-comment'),
    url(r'^news/instructions/$', TemplateView.as_view(template_name="instructions.html"), name='instructions'),
    url(r'^news/faqrecipe/$', TemplateView.as_view(template_name="faqrecipe.html"), name='faqrecipe'),

    url(r'^news/mycomments/$', views.MycommentListView.as_view(), name='mycomments-list'),
    url(r'^news/mycomments/(?P<pk>[0-9]+)/$', views.MycommentDetailView.as_view(), name='mycomments-detail'),
    url(r'^add_mycomment/$', views.add_mycomment, name='add-mycomment'),
]

school/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from payment import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  # url(r'^registration/$', TemplateView.as_view(template_name="registration/reg.html")),
                  url(r'^registration/$', views.TestView.as_view()),
                  url(r'^about/$', TemplateView.as_view(template_name="registration/about.html")),
                  url(r'^faq/$', TemplateView.as_view(template_name="faq.html")),
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'password_change/$', auth_views.password_change,
                      {'template_name': 'registration/change_password.html'},
                      name='password-change'),
                  url(r'password_reset/$', auth_views.password_reset,
                      {'template_name': 'registration/password_reset.html'},
                      name='password-reset'),
                  url(r'^password_reset_done/$', auth_views.password_reset_done,
                      {'template_name': 'registration/password_reset_done.html'},
                      name='password_reset_done'),

                  url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                      auth_views.password_reset_confirm,
                      {'post_reset_redirect': '/password_done/'}, name='password_reset_confirm'),

                  url(r'^password_done/$', auth_views.password_reset_complete),

                  url(r'^password-change-done/$', auth_views.password_change_done,
                      {'template_name': 'registration/password_change_done.html'},
                      name='password_change_done'),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'', include('news.urls')),
                  url(r'^articles/', include('articles.urls')),
                  url(r'^chat/', include('chat.urls')),
                  url(r'^training/', include('training.urls')),
                  url(r'^photorepost/', include('photorepost.urls')),
                  url(r'^food/', include('food.urls')),
                  url(r'^quiz/', include('quiz.urls')),
                  url(r'^users/', include('users.urls')),
                  url(r'^payment/', include('payment.urls')),
                  url(r'^support/', include('supportapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.utils import timezone
from mptt.models import TreeForeignKey, MPTTModel
from ckeditor.fields import RichTextField
from users.models import User


class News(models.Model):
    author = models.ForeignKey('users.User')
    title = models.CharField(max_length=200)
    video = models.TextField(blank=True, null=True, default=None)
    img = models.ImageField(upload_to='news')
    text = RichTextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    is_show = models.BooleanField(default=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Comment(MPTTModel):
    news = models.ForeignKey('news.News', related_name='comments')
    author = models.ForeignKey(User, related_name='author')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=True)
    # parent = models.ForeignKey('self', null=True, blank=True)
    parent = TreeForeignKey('self', blank=True, null=True,
                            related_name='children', db_index=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментария'
        verbose_name_plural = 'Комментарии'



class NewsNewComment(models.Model):
    author = models.ForeignKey(User, related_name='new_author_comments')
    parent = models.ForeignKey(User,related_name='new_parent_comment')
    comment = models.ForeignKey(Comment, related_name='new_comments')


    def __str__(self):
        return str(self.id)

news/forms.py
from django import forms
from .models import News, Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text', 'news','parent',)

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.base import View

from common.mixins import PayCheck
from .models import News, Comment, NewsNewComment
from .forms import CommentForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

class NewsListView(LoginRequiredMixin, PayCheck,ListView):
    model = News
    template_name = 'news/news_list.html'
    context_object_name = 'news'

    def get_queryset(self):
        return News.objects.filter(is_show=True, published_date__lte=timezone.now()).order_by('-published_date')


class NewsDetailView(LoginRequiredMixin, DetailView):
    model = News


    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        comments_list = self.get_object().comments.filter(level=0).order_by('-created_date')

        paginator = Paginator(comments_list, 30)
        page = self.request.GET.get('page')
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments.page(paginator.num_pages)

        ctx['form'] = CommentForm()
        ctx['comments'] = comments
        return ctx

    template_name = 'news/news_detail.html'


def add_comment(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save()

        if comment.parent is None:
            print('no')
            new_comment = ''
        else:
            new_comment = NewsNewComment()
            new_comment.comment = comment
            new_comment.author = comment.author
            new_comment.parent = comment.parent.author
            new_comment.save()

        to_redirect = reverse_lazy('news:detail', kwargs={'pk': comment.news.pk})
        return redirect(to_redirect)


class AddCommentView(LoginRequiredMixin,View):

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            to_redirect = reverse_lazy('news:detail', kwargs={'pk': comment.news.pk})
            return redirect(to_redirect)



class CommentListView(LoginRequiredMixin, PayCheck,ListView):
    model = Comment
    template_name = 'news/comments_list.html'
    context_object_name = 'comments'

    def get_queryset(self):
        return Comment.objects.filter(created_date__lte=timezone.now(),author=self.request.user).order_by('-created_date')[0:18]



class MycommentListView(LoginRequiredMixin, PayCheck,ListView):
    model = News
    template_name = 'comments/comments_list.html'
    context_object_name = 'comments'

    def get_queryset(self):
        return News.objects.filter(is_show=True, published_date__lte=timezone.now()).order_by('-published_date')


class MycommentDetailView(LoginRequiredMixin, DetailView):
    model = News


    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = CommentForm()
        ctx['comments'] = self.get_object().comments.filter(author=self.request.user).order_by('-created_date')
        return ctx

    template_name = 'comments/comments_detail.html'


def add_mycomment(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save()

        if comment.parent is None:
            print('no')
            new_comment = ''
        else:
            new_comment = NewsNewComment()
            new_comment.comment = comment
            new_comment.author = comment.author
            new_comment.parent = comment.parent.author
            new_comment.save()

        to_redirect = reverse_lazy('news:mycomments-detail', kwargs={'pk': comment.news.pk})
        return redirect(to_redirect)



class NotcommentListView(LoginRequiredMixin,ListView):
    model = Comment
    template_name = 'notcomment.html'

    def get(self, request, *args, **kwargs):
        ctx = {}

        #notcomment = Comment.objects.filter(created_date__lte=timezone.now(),author=self.request.user).order_by('-created_date')[0:18]
        notcomment = Comment.objects.filter(parent__author=self.request.user).order_by('-created_date')[:25]

        NewsNewComment.objects.filter(parent=self.request.user).delete()
        comment_counts = NewsNewComment.objects.filter(parent=self.request.user).count()



        ctx['notcomment'] = notcomment
        ctx['comment_counts'] = comment_counts
        return render(request, self.template_name,ctx)

news/templates/news/add_comment_to_news.html
    <h1>New comment</h1>
    <form method="POST" class="news-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

news/templates/news/comments_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}


    <div class="col-md-12 col-sm-12 col-lg-12">

<div class="alert alert-success alert-simple alert-dismissible fade in iconic-alert m-b-lg" role="alert">

							<div class="alert-icon">
								<span class="gcon gcon-emoji-happy centered-xy">Обратите внимание!</span>
							</div>
							<p style="font-size: 12px!important;">Здесь будут показаны все Ваши комментарии и ответы на них.</p>
</div>
        <!-- Комментарии -->
        <div class="panel panel-plain panel-rounded">
            <div class="panel-heading borderless">
                <h3 class="panel-title">Мои комментарии</h3>
            </div><!-- /.panel-heading -->
            <div class="panel-body">





                <ul class="media-list">



                    {% for comment in comments %}




                    <div style="border: 1px solid#eeeeee;padding: 2%;margin-bottom: 5%;">
                        {% for cm in comment.get_family.all %}


                             <li class="media comment-{{ cm.level }}">
                            <div class="media-left media-object-sm">
                                {% thumbnail cm.author.get_avatar "60x60" as im %}
                                    <a href="javascript:void(0);">
                                        <img style="width: 35px; height: 35px;" class="media-object img-circle" src="{{ im.url }}">
                                    </a>
                                {% endthumbnail %}
                            </div><!-- /.media-left -->
                            <div class="media-body">
                                <h6 style="font-weight: 600;" class="media-heading bg-d">{{ cm.author.get_full_name }}</h6>
                                <p style="font-size: 11px;" class="media-subheading text-muted small">{{ cm.created_date }}</p>
                                <p style="font-size: 12px;"> {{ cm.text|linebreaks }}</p>
                            </div><!-- /.media-body -->
                        </li>
                        <hr style="margin-top: 2px;margin-bottom: 2px;">




                    {% endfor %}
                 </div>
                    {% empty %}
                        <p>Нет комментариев здесь :(</p>
                    {% endfor %}

                </ul><!-- /.media-list -->
            </div><!-- .panel-body -->
        </div><!-- End Комментарии -->

        <!-- End Panel -->

    </div><!-- /.col-dm-12 -->




{% endblock %}


{% block breadcrumbs %}
    <li><a href="{% url 'news:list' %}">Новости</a></li>
    <li class="active">{{ object.title }}</li>
{% endblock %}


{% block js_block %}
    <script type="text/javascript">
        $(function(){
            $('.reply-comment').on('click', function(e){
                e.preventDefault();
                var currentUser = $(this).attr('data-user');
                var commentId = $(this).attr('data-comment-id');
                $("#comment-parent").val(commentId);
                $('#comment-text').val(currentUser + ', ');
                $('html,body').stop().animate({ scrollTop: $('#comment-text').offset().top }, 1000);
            })
        });
    </script>
{% endblock %}

news/templates/news/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

news/templates/news/news_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}


    <div class="col-md-12 col-sm-12 col-lg-12">
        <!-- Begin Panel -->
        <div class="panel panel-plain panel-rounded">
            <div class="panel-body p-b-0 text-left">
                <div class="media-body">
                    <h3 class="media-heading">{{ object.title }}</h3>
                    <p class="media-subheading text-muted small">
                        <i class="glyphicon glyphicon-user"></i> {{ object.author.first_name }} {{ object.author.last_name }}
                        <i class="glyphicon glyphicon-time"></i> {{ object.published_date|timesince }}
                    </p>
                    {% if object.video %}

<div class="videoWrapper">
    <!-- Copy & Pasted from YouTube -->

    <video width="560" height="349" controls>
        <source src="{{ object.video }}" type="video/mp4">
    </video>

</div>
 <style>
 .videoWrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
}
.videoWrapper video {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
    border: 1px solid#e1e8ed;
    background: #e1e8ed;
}
 </style>

                    {% endif %}
                    {% autoescape off %}   {{ object.text }} {% endautoescape %}


                    <br>
                    <a target="_blank" href="http://webinar.natalyazubareva.com/"><img style="width: 100%;" src="http://webinar.natalyazubareva.com/zapis.jpg" alt=""></a>
                </div>
            </div><!-- .panel-body -->
        </div><!-- /.panel -->


        <!-- Комментарии -->
        <div {% if request.user.get_tariff_code == 'base' %} style="display: none;" {% endif %} class="panel panel-plain panel-rounded">
            <div class="panel-heading borderless">
                <h3 class="panel-title">Комментарии</h3>
            </div><!-- /.panel-heading -->
            <div class="panel-body">

                <form class="dispaynone"  method="post" action="{% url 'news:add-comment' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Сообщение</label>
                        <input type="hidden" value="{{ object.pk }}" name="{{ form.news.html_name }}">
                        <input type="hidden" id="comment-parent" value="" name="{{ form.parent.html_name }}">

                        <input type="hidden" value="{{ request.user.pk }}" name="{{ form.author.html_name }}">
                        <textarea class="form-control" name="{{ form.text.html_name }}" placeholder="..."
                                  id="comment-text" required style="height: 100px;"></textarea>
                        <button class="btn btn-success btn-block rs-btn-icon icon-block m-b"><span
                                class="fa fa-comment-o icon-btn m-r"></span>Отправить
                        </button>
                    </div>
                </form>
                <br>



                <ul class="media-list  infinite-container">

                    {% for comment in comments %}
                        <li  id="c{{ c.id }}" class="media comment-{{ comment.level }} infinite-item">
                            <div class="media-left media-object-sm">
                                {% thumbnail comment.author.get_avatar "60x60" as im %}
                                    <a href="javascript:void(0);">
                                        <img style="object-fit: none;border: 0.5px solid rgba(74, 137, 220, 0.34);" class="media-object img-circle" src="{{ im.url }}">
                                    </a>
                                {% endthumbnail %}
                            </div><!-- /.media-left -->
                            <div class="media-body">
                                <h4 style="font-size: 16px;" class="media-heading bg-d">{{ comment.author.get_full_name }}</h4>
                                <p class="media-subheading text-muted small">{{ comment.created_date|timesince }} назад</p>
                                <p> {{ comment.text|linebreaks }}</p>
                                <div class="media-footer dispaynone">
                                    <a style="font-size: 11px;border: 1px solid;border-radius: 6px;padding: 0.2% 3px;" data-user="{{ comment.author.get_full_name }}" data-comment-id="{{  comment.pk }}" class="reply-comment" href="">Ответить</a>
                                </div>
                            </div><!-- /.media-body -->
                        </li>
                        <hr>
                        {% for c in comment.get_descendants %}
                        <li  id="c{{ c.id }}" class="media comment-{{ c.level }} infinite-item">
                            <div class="media-left media-object-sm">
                                {% thumbnail c.author.get_avatar "60x60" as im %}
                                    <a href="javascript:void(0);">
                                        <img style="object-fit: none;border: 0.5px solid rgba(74, 137, 220, 0.34);" class="media-object img-circle" src="{{ im.url }}">
                                    </a>
                                {% endthumbnail %}
                            </div><!-- /.media-left -->
                            <div class="media-body">
                                <h4 style="font-size: 16px;" class="media-heading bg-d">{{ c.author.get_full_name }}</h4>
                                <p class="media-subheading text-muted small">{{ c.created_date|timesince }} назад</p>
                                <p> {{ c.text|linebreaks }}</p>
                                <div style="" class="media-footer dispaynone">
                                    <a style="font-size: 11px;border: 1px solid;border-radius: 6px;padding: 0.2% 3px;" data-user="{{ c.author.get_full_name }}" data-comment-id="{{  c.pk }}" class="reply-comment" href="">Ответить</a>
                                </div>
                            </div><!-- /.media-body -->
                        </li>
                        <hr>
                        {% endfor %}

                    {% empty %}
                        <p>Нет комментариев здесь :(</p>
                    {% endfor %}

                </ul><!-- /.media-list -->


  {% if comments.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ comments.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in comments.paginator.page_range %}
      {% if comments.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if comments.has_next %}
      <li><a href="?page={{ comments.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}



            </div><!-- .panel-body -->
        </div><!-- End Комментарии -->

        <!-- End Panel -->

    </div><!-- /.col-dm-12 -->

<div id="someID" class="back-to-bottom bg-dark b-r-a" style="display: block;top: 5px;"><span class="glyphicon glyphicon glyphicon-chevron-down"></span></div>
<style>
 .back-to-bottom {
     position: fixed;
    width: 40px;
    height: 40px;
    z-index: 1000;
    top: 15px;
    right: 5px;
    line-height: 40px;
    cursor: pointer;
    -webkit-box-shadow: 0px 1px 3px 0px rgba(0,0,0,0.08);
    -moz-box-shadow: 0px 1px 3px 0px rgba(0,0,0,0.08);
    box-shadow: 0px 1px 3px 0px rgba(0,0,0,0.08);
    text-align: center;
    display: none;

 }
    .bg-dark {
        background: rgba(46, 49, 61, 0.28) !important;
    }
</style>


{% endblock %}


{% block breadcrumbs %}
    <li><a href="{% url 'news:list' %}">Новости</a></li>
    <li class="active">{{ object.title }}</li>
{% endblock %}


{% block js_block %}
    <script type="text/javascript">
        $(function(){
            $('.reply-comment').on('click', function(e){
                e.preventDefault();
                var currentUser = $(this).attr('data-user');
                var commentId = $(this).attr('data-comment-id');
                $("#comment-parent").val(commentId);
                $('#comment-text').val(currentUser + ', ');
                $('html,body').stop().animate({ scrollTop: $('#comment-text').offset().top }, 1000);
            })
        });
        $(function(){
                $('#someID').click(function(){
                     $('html, body').animate({scrollTop:$(document).height()}, 'slow');
                    return false;
                });
        });
    </script>
{% endblock %}

news/templates/news/news_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}

    {% for news_one in news %}
        <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12" style="min-height: 300px;">
            <!-- Begin Panel -->
            <div class="panel panel-plain panel-rounded">
                <div class="panel-heading borderless">
                    <div class="media-left media-object-sm">
                        {% thumbnail news_one.author.get_avatar "60x60" as im %}
                            <img  src="{{ im.url }}" alt="Avatar" class="media-object img-circle">
                        {% endthumbnail %}


                    </div>
                    <div class="media-body">
                        <p class="media-subheading text-muted small news-date">{{ news_one.published_date|timesince }} назад</p>
                        <h6 class="media-heading">{{ news_one.author.first_name }} {{ news_one.author.last_name }}</h6>
                    </div>

                </div><!-- /.panel-heading -->
                <a class="url-news" href="{% url 'news:detail' news_one.pk %}">

                    <div class="panel-body p-t-0 text-center">
                        <style>
                            .news__detail_img{
                                background-repeat: no-repeat;
                                height: 260px;
                                background-size:100% auto;
                                 background-position: top;
                                display: block;
                            }
                            @media (max-width: 1024px){
                                .news__detail_img{
                                    width: 100%;
                                    height: 240px;
                                }
                            }
                            @media (max-width: 667px){
                                .news__detail_img{
                                    width: 100%;
                                    height: 208px;
                                }
                            }
                            @media (max-width: 322px){
                                .news__detail_img{
                                    width: 100%;
                                    height: 160px;
                                }
                            }



                        </style>
                         {% thumbnail news_one.img "421x288" as im %}

                                <div class="news__detail_img" style="background-image: url({{ im.url }});"></div>

                        {% endthumbnail %}
                    </div><!-- .panel-body -->
                </a>
                    <div class="panel-body p-t-0 text-left" style="min-height: 100px;">
                         <h6 class="panel-title"><a href="{% url 'news:detail' news_one.pk %}">{{ news_one.title }}</a></h6>

                    </div><!-- .panel-body -->
                </a>
            </div><!-- /.panel -->
            <!-- End Panel -->

        </div><!-- /.col-dm-6 -->

    {% endfor %}

{% endblock %}