articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'
urlpatterns = [
    url(r'^$', views.ArticlesListView.as_view(), name='list'),
    url(r'^articles/(?P<pk>[0-9]+)/$', views.ArticlesDetailView.as_view(), name='detail'),
    url(r'^add_comment/$', views.add_comment, name='add-comment'),
]

chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.MessageListView.as_view(), name='list'),
    url(r'^testmessage/$', views.MessageListTestView.as_view(), name='test-list'),
    url(r'^error/$', views.MessageErrorView.as_view(), name='error'),
    url(r'^consultant-room/(?P<pk>[0-9]+)$', views.MessageRoomView.as_view(), name='consultant-room'),
    url(r'^tbase-room/(?P<pk>[0-9]+)$', views.TBaseMessageRoomView.as_view(), name='tbase-room'),
    url(r'^search/$', views.UserSearchView.as_view(), name='search'),
]

school/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from payment import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  # url(r'^registration/$', TemplateView.as_view(template_name="registration/reg.html")),
                  url(r'^registration/$', views.TestView.as_view()),
                  url(r'^about/$', TemplateView.as_view(template_name="registration/about.html")),
                  url(r'^faq/$', TemplateView.as_view(template_name="faq.html")),
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'password_change/$', auth_views.password_change,
                      {'template_name': 'registration/change_password.html'},
                      name='password-change'),
                  url(r'password_reset/$', auth_views.password_reset,
                      {'template_name': 'registration/password_reset.html'},
                      name='password-reset'),
                  url(r'^password_reset_done/$', auth_views.password_reset_done,
                      {'template_name': 'registration/password_reset_done.html'},
                      name='password_reset_done'),

                  url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                      auth_views.password_reset_confirm,
                      {'post_reset_redirect': '/password_done/'}, name='password_reset_confirm'),

                  url(r'^password_done/$', auth_views.password_reset_complete),

                  url(r'^password-change-done/$', auth_views.password_change_done,
                      {'template_name': 'registration/password_change_done.html'},
                      name='password_change_done'),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'', include('news.urls')),
                  url(r'^articles/', include('articles.urls')),
                  url(r'^chat/', include('chat.urls')),
                  url(r'^training/', include('training.urls')),
                  url(r'^photorepost/', include('photorepost.urls')),
                  url(r'^food/', include('food.urls')),
                  url(r'^quiz/', include('quiz.urls')),
                  url(r'^users/', include('users.urls')),
                  url(r'^payment/', include('payment.urls')),
                  url(r'^support/', include('supportapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from common.models import KnowledgeLevel
from mptt.models import TreeForeignKey, MPTTModel
from users.models import User


class Articles(models.Model):
    author = models.ForeignKey('users.User')
    title = models.CharField(max_length=200)
    img = models.ImageField(upload_to='articles')
    text = RichTextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    knowledge = models.ForeignKey(KnowledgeLevel, related_name='articles',
                                  null=True, blank=True)
    is_show = models.BooleanField(default=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-published_date',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(MPTTModel):
    article = models.ForeignKey(Articles, related_name='article_comments')
    author = models.ForeignKey(User)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=True)
    parent = TreeForeignKey('self', blank=True, null=True,
                            related_name='children', db_index=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

articles/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text', 'article', 'parent',)

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView

from common.mixins import PayCheck
from .models import Articles
from .forms import CommentForm


class ArticlesListView(LoginRequiredMixin, PayCheck, ListView):
    model = Articles
    template_name = 'articles/articles_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        knowledge = self.request.user.knowledge
        custom_kwargs = dict()
        custom_kwargs['knowledge'] = knowledge
        custom_kwargs['published_date__lte'] = timezone.now()

        if self.request.user.is_food_user():
            custom_kwargs['author__type__in'] = ['zubareva']
        elif self.request.user.is_food_plus_sport_user():
            custom_kwargs['author__type__in'] = ['zubareva','coach','neurologist']
        elif self.request.user.is_food_plus_specialist_user():
            custom_kwargs['author__type__in'] = ['zubareva','neurologist','gastro','psychologist','gv','gynecologist','endoc']
        elif self.request.user.is_children_user():
            custom_kwargs['author__type__in'] = ['zubareva', 'pediatrician', 'gv']
        elif self.request.user.is_family_user():
            custom_kwargs['knowledge'] = knowledge
        elif self.request.user.is_articles_access():
            pass
        else:
            return Articles.objects.filter(is_show=True, published_date__lte=timezone.now())\
                                .order_by('-published_date')

        return Articles.objects.filter(is_show=True, **custom_kwargs).order_by('-published_date')


class ArticlesDetailView(LoginRequiredMixin,DetailView):
    model = Articles
    template_name = 'articles/articles_detail.html'

    def dispatch(self, request, *args, **kwargs):
        # article = self.get_object()
        # current_user = self.request.user
        # if not current_user.is_consultant_manager():
        #     if article.knowledge != current_user.knowledge:
        #         raise Http404
            # if current_user.is_food_user() and article.author.type in ['zubareva']:
            #     raise Http404
            # if current_user.is_food_plus_sport_user() and article.author.type in ['zubareva','coach']:
            #     raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = CommentForm()
        return ctx


def add_comment(request):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save()
        to_redirect = reverse_lazy('articles:detail', kwargs={'pk': comment.article.pk})
        return redirect(to_redirect)

articles/templates/articles/articles_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}


    <div class="col-md-12 col-sm-12 col-lg-12">
        <!-- Begin Panel -->
        <div class="panel panel-plain panel-rounded">
            <div class="panel-body p-b-0 text-left">
                <div class="media-body">
                    <h3 class="media-heading">{{ object.title }}</h3>
                    <p class="media-subheading text-muted small">
                        <i class="glyphicon glyphicon-user"></i> {{ object.author.first_name }} {{ object.author.last_name }}
                        <i class="glyphicon glyphicon-time"></i> {{ object.published_date|timesince }}
                    </p>
                    {% autoescape off %}   {{ object.text }} {% endautoescape %}
                </div>
            </div><!-- .panel-body -->
        </div><!-- /.panel -->


        <!-- Комментарии -->
        <div style="display:none;"  class="panel panel-plain panel-rounded">
            <div class="panel-heading borderless">
                <h3 class="panel-title">Комментарии</h3>
            </div><!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="media-list">
                    {% for c in object.article_comments.all %}
                        <li class="media comment-{{ c.level }}">
                            <div class="media-left media-object-sm">
                                {% thumbnail c.author.get_avatar "60x60" as im %}
                                    <a href="javascript:void(0);">
                                        <img class="media-object img-circle" src="{{ im.url }}">
                                    </a>
                                {% endthumbnail %}
                            </div><!-- /.media-left -->
                            <div class="media-body">
                                <h4 class="media-heading bg-d">{{ c.author.get_full_name }}</h4>
                                <p class="media-subheading text-muted small">{{ c.created_date }}</p>
                                <p> {{ c.text|linebreaks }}</p>
                                <div class="media-footer">
                                    <a data-user="{{ c.author.get_full_name }}" data-comment-id="{{ c.pk }}" class="reply-comment" href="">Ответить</a>
                                </div>
                            </div><!-- /.media-body -->
                        </li>
                        <hr>
                    {% endfor %}

                </ul><!-- /.media-list -->
                <form method="post" action="{% url 'articles:add-comment' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Сообщение</label>
                        <input type="hidden" value="{{ object.pk }}" name="{{ form.article.html_name }}">
                        <input type="hidden" id="comment-parent" value="" name="{{ form.parent.html_name }}">
                        <input type="hidden" value="{{ request.user.pk }}" name="{{ form.author.html_name }}">
                                                <textarea class="form-control" id="comment-text" name="{{ form.text.html_name }}"
                                                          placeholder="Textarea" style="height: 100px;"></textarea>
                        <button type="submit" class="btn btn-success btn-block rs-btn-icon icon-block m-b"><span
                                class="fa fa-comment-o icon-btn m-r"></span>Отправить
                        </button>
                    </div>
                </form>
            </div><!-- .panel-body -->
        </div><!-- End Комментарии -->

        <!-- End Panel -->

    </div><!-- /.col-dm-12 -->




{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'articles:list' %}">Статьи</a></li>
    <li class="active">{{ object.title }}</li>
{% endblock %}

{% block js_block %}
    <script type="text/javascript">
        $(function(){
            $('.reply-comment').on('click', function(e){
                e.preventDefault();
                var currentUser = $(this).attr('data-user');
                var commentId = $(this).attr('data-comment-id');
                $("#comment-parent").val(commentId);
                $('#comment-text').val(currentUser + ', ');
                $('html,body').stop().animate({ scrollTop: $('#comment-text').offset().top }, 1000);
            })
        });
    </script>
{% endblock %}

articles/templates/articles/articles_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}

    {% for articles_one in articles %}
        <div class="col-md-6 col-sm-6 col-lg-6" style="min-height: 300px;">
            <!-- Begin Panel -->
            <div class="panel panel-plain panel-rounded">
                <div class="panel-heading borderless">
                    <div class="media-left media-object-sm">
                        {% thumbnail articles_one.author.get_avatar "60x60" as im %}
                            <img  src="{{ im.url }}" alt="Avatar" class="media-object img-circle">
                        {% endthumbnail %}

                    </div>
                    <div class="media-body">
                        <p class="media-subheading text-muted small news-date">{{ articles_one.published_date|timesince }}</p>
                        <h6 style="font-size: 10px;" class="media-heading">{{ articles_one.author.first_name }} {{ articles_one.author.last_name }}</h6>
                    </div>

                </div><!-- /.panel-heading -->
                <a class="url-news" href="{% url 'articles:detail' articles_one.pk %}">

                    <div class="panel-body p-t-0 text-center">
                        {% thumbnail articles_one.img "421x288" as im %}

                                <img style="width: 100%; height: 288px;object-fit: cover; transition: all .25s ease;"  class="img-responsive" src="{{ im.url }}" alt="{{ articles_one.title }}">

                        {% endthumbnail %}
                    </div><!-- .panel-body -->
                    <div class="panel-body p-t-0 text-left" style="min-height: 60px;">
                         <h6 class="panel-title">{{ articles_one.title }}</h6>
                    </div><!-- .panel-body -->
                </a>
            </div><!-- /.panel -->
            <!-- End Panel -->

        </div><!-- /.col-dm-6 -->
    {% endfor %}

{% endblock %}

{% block breadcrumbs %}
    <li class="active">Статьи</li>
{% endblock %}