chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.MessageListView.as_view(), name='list'),
    url(r'^testmessage/$', views.MessageListTestView.as_view(), name='test-list'),
    url(r'^error/$', views.MessageErrorView.as_view(), name='error'),
    url(r'^consultant-room/(?P<pk>[0-9]+)$', views.MessageRoomView.as_view(), name='consultant-room'),
    url(r'^tbase-room/(?P<pk>[0-9]+)$', views.TBaseMessageRoomView.as_view(), name='tbase-room'),
    url(r'^search/$', views.UserSearchView.as_view(), name='search'),
]

school/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from payment import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  # url(r'^registration/$', TemplateView.as_view(template_name="registration/reg.html")),
                  url(r'^registration/$', views.TestView.as_view()),
                  url(r'^about/$', TemplateView.as_view(template_name="registration/about.html")),
                  url(r'^faq/$', TemplateView.as_view(template_name="faq.html")),
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'password_change/$', auth_views.password_change,
                      {'template_name': 'registration/change_password.html'},
                      name='password-change'),
                  url(r'password_reset/$', auth_views.password_reset,
                      {'template_name': 'registration/password_reset.html'},
                      name='password-reset'),
                  url(r'^password_reset_done/$', auth_views.password_reset_done,
                      {'template_name': 'registration/password_reset_done.html'},
                      name='password_reset_done'),

                  url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                      auth_views.password_reset_confirm,
                      {'post_reset_redirect': '/password_done/'}, name='password_reset_confirm'),

                  url(r'^password_done/$', auth_views.password_reset_complete),

                  url(r'^password-change-done/$', auth_views.password_change_done,
                      {'template_name': 'registration/password_change_done.html'},
                      name='password_change_done'),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'', include('news.urls')),
                  url(r'^articles/', include('articles.urls')),
                  url(r'^chat/', include('chat.urls')),
                  url(r'^training/', include('training.urls')),
                  url(r'^photorepost/', include('photorepost.urls')),
                  url(r'^food/', include('food.urls')),
                  url(r'^quiz/', include('quiz.urls')),
                  url(r'^users/', include('users.urls')),
                  url(r'^payment/', include('payment.urls')),
                  url(r'^support/', include('supportapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^profile/edit/$', views.UserProfileEditView.as_view(), name='profile-edit'),
    url(r'^profile/add_in_group/$', views.UserAddToInGroupView.as_view(), name='add-in-group'),
    url(r'^profile/family/edit/(?P<pk>[0-9]+)/$', views.UserProfileFamilyEditView.as_view(), name='profile-family-edit'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/password-edit/$', views.UserPasswordEditView.as_view(), name='password-edit'),
    url(r'^all/$', views.users_list, name='users-list'),
]

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import User
from django.forms import Select
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from common.models import KnowledgeLevel


class UserFamilyEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'avatar',
            'phone',
            'instagram',
            'gender',
            'height',
            'weight',
            'age',
            'lifestyle',
            'goal',
        )
        widgets = {
              'lifestyle': Select(attrs={'class': 'form-control'}),
          }

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar', False)
        if avatar:
            if avatar.size > settings.MAX_UPLOAD_SIZE:
                raise ValidationError('Аватарка больше 4 мегабайтов')
            return avatar


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'avatar',
                  'phone',
                  'instagram',
                  'gender',
                  'height',
                  'weight',
                  'age',
                  'lifestyle',
                  'goal',
                  )
        widgets = {
              'lifestyle': Select(attrs={'class': 'form-control'}),
          }

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar', False)
        if avatar:
            if avatar.size > settings.MAX_UPLOAD_SIZE:
                raise ValidationError('Аватарка больше 4 мегабайтов')
            return avatar

RATES_CHOICES = (
    ('base', 'Базовый 3000₽'),
    ('food', 'Питание 3700₽'),
    ('children', 'Детский 4100₽'),
    ('food_plus_sport', 'Питание и спорт 4600₽'),
    ('food_plus_specialist', 'Питание и специалисты 4900₽'),
    ('pregnancy', 'Беременность 5000₽'),
    ('all_inclusive', 'Все включено для взрослых 6000₽'),
    ('family', 'Семейный 7000₽'),
)


class UserRegistrationForm(forms.Form):
    first_name = forms.CharField(label="Имя",max_length=100)
    last_name = forms.CharField(label="Фамилия", max_length=100)
    email = forms.EmailField(label="E-mail")
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label="Повторите пароль",
        widget=forms.PasswordInput,
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )
    knowledge = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), queryset=KnowledgeLevel.objects.all())
    rate = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), choices=RATES_CHOICES)
    promocod = forms.CharField(label="Промокод",max_length=100, required=False)

    def clean_email(self):
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError("Пользователь с таким email уже зарегистрирован в системе.")
        return self.cleaned_data['email']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Ваши пароли не совпадают")
        # self.instance.username = self.cleaned_data.get('username')
        # password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     user.set_password(self.cleaned_data["password1"])
    #     if commit:
    #         user.save()
    #     return user


class ProlongForm(forms.Form):
    knowledge = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), queryset=KnowledgeLevel.objects.all())
    rate = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), choices=RATES_CHOICES)
    promocod = forms.CharField(label="Промокод",max_length=100, required=False)


class AddUserInGroupForm(forms.Form):
    first_name = forms.CharField(label="Имя",max_length=100)
    last_name = forms.CharField(label="Фамилия", max_length=100)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.views.generic import DetailView, View,TemplateView
from django.core.urlresolvers import reverse_lazy

from common.models import KnowledgeLevel
from common.mixins import PayCheck
from users.forms import UserEditForm,UserFamilyEditForm, AddUserInGroupForm
from .models import User, Family


class UserProfileEditView(LoginRequiredMixin, PayCheck, View):
    template_name = 'users/profile_edit.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        form = UserEditForm(instance=user)
        user_weight = user.weight
        ctx = dict()
        ctx['form'] = form
        ctx['user'] = user

        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        form = UserEditForm(request.POST,request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save()
            return redirect(reverse_lazy('users:profile'))
        else:
            return render(request, self.template_name,{
                'form': form,
                'user': request.user,
            })


class UserProfileFamilyEditView(LoginRequiredMixin, View):
    template_name = 'users/profile_family_edit.html'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs.get('pk'))
        form = UserFamilyEditForm(instance=user)
        ctx = dict()
        ctx['form'] = form
        return render(request,self.template_name,ctx)

    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs.get('pk'))
        form = UserFamilyEditForm(request.POST,request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect(reverse_lazy('users:profile'))
        else:
            return render(request, self.template_name,{
                'form': form,
                'user': request.user,
            })


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'users/profile.html'

    def get_kbj(self, user):
        user_attrs = [user.weight, user.height, user.age,
                      user.gender, user.lifestyle, user.goal]
        if all(user_attrs):
            if user.gender == 'F':
                voo = user.weight * 9.99 + 6.25 * user.height - 4.92 * user.age - 161
            elif user.gender == 'M':
                voo = user.weight * 9.99 + 6.25 * user.height - 4.92 * user.age + 5

            voo = voo * user.lifestyle.coef
            if user.goal == 'lose':
                res = (voo/100) * 20
                res_voo = voo - res
            elif user.goal == 'gain':
                res = (voo/100) * 20
                res_voo = voo + res
            elif user.goal == 'maintain':
                res_voo = voo
            proteins = (res_voo/100) * 30
            fats = (res_voo/100) * 30
            carbs = (res_voo/100) * 40
            proteins = proteins / 4
            fats = fats / 8
            carbs = carbs / 4

            results = {
                'proteins' : proteins,
                'fats': fats,
                'carbs': carbs,
                'calories': res_voo,
            }
        else:
            results = {
                'proteins': 0,
                'fats': 0,
                'carbs': 0,
                'calories': 0,
            }

        return results

    def get(self, request, *args, **kwargs):
        ctx = dict()
        ctx['results'] = self.get_kbj(request.user)
        if request.user.is_family_user():
            ctx['family_users'] = request.user.get_family_users()
        elif request.user.is_children_user():
            ctx['family_users'] = request.user.get_family_users()

        return render(request, self.template_name, ctx)


class UserAddToInGroupView(LoginRequiredMixin, View):

    template_name ='users/add_user_in_group_family.html'

    def get(self, request, *args, **kwargs):
        form = AddUserInGroupForm()
        ctx = dict()
        ctx['form'] = form
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        print(request.POST)
        form = AddUserInGroupForm(request.POST)
        common_id = request.user.id + 1000
        error = ''
        c = Family.objects.filter(common_id=common_id).count()
        group = request.user.get_tariff()
        if group.name == 'family':
            col = 2
        elif group.name == 'children':
            col = 1

        if c > col:
            error = 'Вы не можете'
        elif form.is_valid():
            user = User()
            user.set_password('159159147')
            email = str(request.user.id) + str(c) + request.user.email
            user.username = email
            user.email = email
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')

            user.save()
            group.user_set.add(user)

            f = Family()
            f.user = user
            f.common_id = common_id
            f.type = group.name
            f.save()

            f_current = Family.objects.get_or_create(
                user=request.user,
                common_id = common_id,
                type = group.name
            )

            print('=========================================================================')
            print(group)
            return redirect(reverse_lazy('users:profile'))
        ctx = dict()
        ctx['form'] = form
        ctx['error'] = error
        return render(request, self.template_name, ctx)

class UserPasswordEditView(LoginRequiredMixin, TemplateView):
    template_name = 'users/change_password.html'


def users_list(request):
    import csv
    users = []
    with open('users.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
        for row in spamreader:
            new_user = {
                'email': row[3],
                'tariff': row[1],
                'level': row[2],
            }
            users.append(new_user)

    print(len(users))
    c = 0
    for user in users:
        group = Group.objects.filter(name=user['tariff']).first()
        knowledge = KnowledgeLevel.objects.filter(code=user['level']).first()
        user_yes = User.objects.filter(email=user['email']).first()
        user_yes.knowledge=knowledge
        user_yes.save()
        if not user_yes:
            if group and knowledge:
                n_user = User.objects.create_user(username=user['email'],
                                 email=user['email'],
                                 password='159159147', knowledge=knowledge)
                group.user_set.add(n_user)
                print(group)
                c +=1
            print(c)
    return render(request, 'users/users_list.html', {
        'users': users,
    })

users/templates/users/add_user_in_group_family.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}

    <!-- Begin Panel -->
    <div class="panel panel-plain panel-rounded">
        <div class="panel-heading">
            <h3 class="panel-title">Добавление дополнительного пользователя</h3>
            <!-- End Panel Toolbar -->
        </div>
        <br>
        <div class="panel-body p-t-xs">



<form method="post" action="">{% csrf_token %}
    <div>{{ form.errors }}</div>
    <div>{{ error }}</div>
<div class="row">

    <div class="col-md-8">
        <div class="form-group">
            <label for="">Имя</label>
            <input type="text"  class="form-control" name="{{ form.first_name.html_name}}" value="{{ form.first_name.value|default_if_none:''}}">
        </div>
    </div>
    <br>
    <div class="col-md-8">
        <div class="form-group">
            <label for="">Фамилия</label>
            <input type="text"  class="form-control" name="{{ form.last_name.html_name}}" value="{{ form.last_name.value|default_if_none:''}}">
        </div>
    </div>


    <div class="col-md-8">
        <input type="submit" class="btn btn-info" value="Добавить">
    </div>
</div>
</form>

        </div><!-- .panel-body -->
    </div><!-- /.panel -->
    <!-- End Panel -->

{% endblock %}

users/templates/users/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}

    <!-- Begin Panel -->
    <div class="panel panel-plain panel-rounded">
        <div class="panel-heading">
            <h3 class="panel-title">Изменить пароль</h3>
            <!-- End Panel Toolbar -->
        </div>
        <br>
        <div class="panel-body p-t-xs">


            <form method="post" enctype="multipart/form-data">


                <div class="row">
                    <div class="col-md-6  col-md-offset-3">
                        <div class="form-group">
                            <label>Новый пароль:</label>
                            <input type="text" class="form-control" value="">
                        </div>
                    </div><!-- /.col-md-6 -->
                    <div class="col-md-6  col-md-offset-3">
                        <div class="form-group">
                            <label>Повторите новый пароль:</label>
                            <input type="text" class="form-control" value="">
                        </div>
                    </div><!-- /.col-md-6 -->

                    <div class="col-md-6 col-md-offset-3">
                        <input type="submit" class="btn btn-info" value="Сохранить">
                    </div>


                </div><!-- /.row -->

            </form>
        </div><!-- .panel-body -->
    </div><!-- /.panel -->
    <!-- End Panel -->

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}
<!-- Begin Panel -->



        {% if request.user.get_tariff_code == 'family' %}
 <div class="panel panel-plain panel-rounded">
<div class="panel-body">
<div class="row">
    <div class="col-md-2 col-md-offset-9 col-xs-12">


            <a class="btn btn-success" href="https://zubareva.online/users/profile/add_in_group/">Добавить пользователя</a>
    </div>
</div>
</div>
</div>
        {% elif request.user.get_tariff_code == 'children' %}
<div class="panel panel-plain panel-rounded">
<div class="panel-body">
<div class="row">
    <div class="col-md-2 col-md-offset-9 col-xs-12">


            <a class="btn btn-success" href="https://zubareva.online/users/profile/add_in_group/">Добавить пользователя</a>
    </div>
</div>
</div>
</div>
        {% else %}
        {% endif %}


<div class="panel panel-plain panel-rounded">
    <div class="panel-heading borderless">
        <h2 class="panel-title">Профиль</h2>
        <!-- Begin Panel Toolbar -->
        <div class="panel-toolbar">
            <a href="{% url 'users:profile-edit' %}" style="height: 22px; padding-top:0;"
               class="btn btn-info btn-outline btn-block rs-btn-icon m-b">
                <span style="line-height:20px;" class="fa fa-gear icon-btn m-r"></span>Редактировать</a>
        </div><!-- /.panel-toolbar -->
        <!-- End Panel Toolbar -->
    </div>
    <br>



    <div class="panel-body p-t-xs">

        <div class="stacked-item panel panel-primary bg-primary">
                    <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">


                {% thumbnail request.user.avatar "190x190" as im %}
                <img style="width: 100%;" src="{{ im.url }}">
                {% endthumbnail %}

            </div>
            <div class="col-xs-12 col-sm-6 col-md-9">




								<div class="panel-heading borderless">
									<h3 class="panel-title">{{ request.user.first_name }} {{ request.user.last_name }}</h3>
									<p class="subtitle text-uppercase m-t-xs">
                                        <i class="fa fa-instagram text-info m-r-xs"></i> {{ request.user.instagram }}
                                    </p>
								</div><!-- /.panel-heading -->
								<div class="panel-body p-t-0">
									<small class="text-lighten">Тариф: <strong class="text-white">{{ request.user.get_tariff_name }}</strong></small><br>
                                    <small class="text-lighten">Уровень: <strong class="text-white">{{ request.user.knowledge }}</strong></small><br>
								</div><!-- /.panel-body -->
							</div>
   </div>



        </div>
                    <div class="row">
                         <div class="panel-heading borderless">
                             <h3 class="panel-title">КБЖУ</h3></div>
									<div class="col-sm-3">
										<!-- Begin Panel -->
										<div class="quick-stat panel panel-rounded bg-grad bg-grad-01 borderless">
											<div class="panel-heading borderless">
												<p class="subtitle text-lighten text-uppercase m-b-xs">Ккал</p>
												<h3 class="m-a-0 p-a-0">{{ results.calories|floatformat:2 }}</h3>
												<!-- End Panel Toolbar -->
											</div><!-- /.panel-heading -->
										</div><!-- /.panel -->
										<!-- End Panel -->
									</div><!-- /.col-sm-4 -->
									<div class="col-sm-3">
										<!-- Begin Panel -->
										<div class="quick-stat panel panel-rounded bg-grad bg-grad-05 borderless">
											<div class="panel-heading borderless">
												<p class="subtitle text-lighten text-uppercase m-b-xs">Белки</p>
												<h3 class="m-a-0 p-a-0">{{ results.proteins|floatformat:2 }}</h3>
												<!-- End Panel Toolbar -->
											</div><!-- /.panel-heading -->
										</div><!-- /.panel -->
										<!-- End Panel -->
									</div><!-- /.col-sm-4 -->
									<div class="col-sm-3">
										<!-- Begin Panel -->
										<div class="quick-stat panel panel-rounded bg-grad bg-grad-03 borderless">
											<div class="panel-heading borderless">
												<p class="subtitle text-lighten text-uppercase m-b-xs">Жиры</p>
												<h3 class="m-a-0 p-a-0">{{ results.fats|floatformat:2 }}</h3>

												<!-- End Panel Toolbar -->
											</div><!-- /.panel-heading -->
										</div><!-- /.panel -->
										<!-- End Panel -->
									</div><!-- /.col-sm-4 -->
									<div class="col-sm-3">
										<!-- Begin Panel -->
										<div class="quick-stat panel panel-rounded bg-grad bg-grad-15 borderless">
											<div class="panel-heading borderless">
												<p class="subtitle text-lighten text-uppercase m-b-xs">Углеводы</p>
												<h3 class="m-a-0 p-a-0">{{ results.carbs|floatformat:2 }}</h3>
												<!-- End Panel Toolbar -->
											</div><!-- /.panel-heading -->
										</div><!-- /.panel -->
										<!-- End Panel -->
									</div><!-- /.col-sm-4 -->

                        <div class="col-xs-12 col-sm-12 col-md-12">

                            <div class="alert alert-success alert-simple alert-dismissible fade in m-b-lg" role="alert">

							<p style="font-size: 12px!important;"> Для расчета КБЖУ заполните все поля на странице "<a href="/users/profile/edit/">редактирование профиля</a>"</p>
                                <p><strong>Зачем это нужно?</strong><br>
                                    <span style="font-size: 12px!important;line-height: 1.5;">позволяет получить ответ на:</span>
                                </p>

                                <ul style="font-size: 12px!important;line-height: 1.5;">
                                    <li>Сколько калорий, белков, жиров и углеводов вам нужно?</li>
                                    <li>Насколько нужно увеличить или уменьшить норму калорий, чтобы плавно худеть или набирать вес?</li>
                                    <li>Достаточно ли жиров и белков вы едите?</li>
                                </ul>
</div>

                        </div>
                    </div>




    </div><!-- .panel-body -->

</div><!-- /.panel -->
<!-- End Panel -->

    {% for f_user in family_users %}

<div class="panel panel-plain panel-rounded">
    <div class="panel-heading borderless">
        <!-- Begin Panel Toolbar -->
        <div class="panel-toolbar">
            <a href="{% url 'users:profile-family-edit' f_user.id  %}" style="height: 22px; padding-top:0;"
               class="btn btn-info btn-outline btn-block rs-btn-icon m-b">
                <span style="line-height:20px;" class="fa fa-gear icon-btn m-r"></span>Редактировать</a>
        </div><!-- /.panel-toolbar -->
        <!-- End Panel Toolbar -->
    </div>
    <br>

    <div class="panel-body p-t-xs">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">


                {% thumbnail f_user.avatar "190x190" as im %}
                <img style="margin:0 auto;" class="thumbnail" src="{{ im.url }}">
                {% endthumbnail %}
                <br>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-9">
                <h5 class="media-heading bg-d">{{ f_user.first_name }} {{ f_user.last_name }} <span style="display:none; font-size:10px;color: rgb(74, 137, 220);">{{ f_user.email}}</span></h5>

                <p class="media-subheading text-muted">
                    <i class="fa fa-instagram text-info m-r-xs"></i>
                    <small>{{ f_user.instagram }}</small>
                </p>
                <div class="rs-col-stacked full-width-on-mobile border-items borderless m-a-0">
                    <div class="text-center stacked-item p-a-md p-b-lg">
                        <div class="easypiechart easypie-info text-muted" data-percent="55">
                            <span class="text-info">{{ f_user.get_kbj.calories|floatformat:2 }}</span>
                            <small>Ккал</small>
                            <canvas height="80" width="80"></canvas>
                        </div><!-- /.easypiechart -->
                    </div><!-- /.stacked-item -->
                    <div class="text-center stacked-item p-a-md p-b-lg">
                        <div class="easypiechart easypie-warning text-muted" data-percent="35">
                            <span class="text-warning">{{ f_user.get_kbj.proteins|floatformat:2 }}</span>
                            <small>Белки</small>
                            <canvas height="80" width="80"></canvas>
                        </div><!-- /.easypiechart -->
                    </div><!-- /.stacked-item -->
                    <div class="text-center stacked-item p-a-md p-b-lg">
                        <div class="easypiechart easypie-danger text-muted" data-percent="15">
                            <span class="text-danger">{{ f_user.get_kbj.fats|floatformat:2 }}</span>
                            <small>Жиры</small>
                            <canvas height="80" width="80"></canvas>
                        </div><!-- /.easypiechart -->
                    </div><!-- /.stacked-item -->
                    <div class="text-center stacked-item p-a-md p-b-lg">
                        <div class="easypiechart easypie-danger text-muted" data-percent="18">
                            <span class="text-danger">{{ f_user.get_kbj.carbs|floatformat:2 }}</span>
                            <small>Углеводы</small>
                            <canvas height="80" width="80"></canvas>
                        </div><!-- /.easypiechart -->
                    </div><!-- /.stacked-item -->

                </div>

            </div>

        </div>
    </div><!-- .panel-body -->

    </div><!-- /.panel -->
<!-- End Panel -->

    {% endfor %}






{% endblock %}


{% block breadcrumbs %}
    <li>Профиль</li>
{% endblock %}

users/templates/users/users_list.html
<h1>Пользователи</h1>

<table border="0">
    <thead>
       <tr>
           <th></th>
           <th>Email</th>
           <th>Tarif</th>
           <th>Level</th>
       </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.tariff }}</td>
          <td>{{ user.level }}</td>
      </tr>
    {% endfor %}
    </tbody>
</table>